meme_app/config/routes.rb
Rails.application.routes.draw do
  resources :items
  mount_devise_token_auth_for 'User', at: 'auth'
  namespace :api do
    namespace :v1 do
      resources :users
      resources :memes
      post '/memes/upvote/:id', to: 'memes#increase_vote', as: 'meme_upvote'
    end
  end

  post 'authenticate', action: :authenticate, controller: 'api/v1/authentication'
  post 'current_user', action: :current_user, controller: 'api/v1/authentication'
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

meme_app/app/models/meme.rb
class Meme < ApplicationRecord
    has_many :users, through: :votes
    has_one_attached :link

end

meme_app/app/controllers/api/v1/memes_controller.rb
require 'pry'

class Api::V1::MemesController < ApplicationController
  before_action :set_meme, only: [:show, :update, :destroy]
  skip_before_action :authenticate_request

  # GET /memes
  def index
    @memes = Meme.all
    @meme_array = []
    @memes.map do | meme |
      @name = User.find(meme.user_id).name
      if (meme.link.attached?)
       link = Rails.application.routes.url_helpers.rails_blob_path(meme.link, only_path: true)
       @meme_array.push({ :meme => meme, :link => link, :name => @name})
      end
    end
    # sort for highest to lowest upvote
    if (params[:sort])
      @meme_array = @meme_array.sort_by { |meme| meme[:meme][:votes] }.reverse! 
    end
    render json: @meme_array
  end

  def increase_vote
    @meme = Meme.find_by_id(params[:id])
    @user = User.find_by_id(params[:user])
    @vote_allowed = false
    @vote_instance = Vote.new(meme_id: @meme.id, user_id: @user.id)
    if @vote_instance.save
      @meme.votes = @meme.votes + 1
      @meme.save
      @vote_allowed = true
    end
    render json: { meme: @meme, permitted: @vote_allowed }
  end

  # GET /memes/1
  # GET /memes/1.json
  def show
    render json: @meme
  end

  # GET /memes/1/edit
  def edit
  end

  # POST /memes
  # POST /memes.json
  def create
    @meme = Meme.new(meme_params)
    @meme.link.attach(params[:meme][:link])
    # @meme.link.attach(io: File.open("/path/to/#{[:me]}.jpg"), filename: "pic.jpg", content_type: "image/jpg")
   if @meme.save
      render json: @meme, status: :created, location: api_v1_meme_url(@meme)
    else 
      render json: @meme.errors, status: :unprocessable_entity
    end 
  end

  # # PATCH/PUT /memes/1
  # # PATCH/PUT /memes/1.json
  # def update
  #     if @meme.update(meme_params)
  #       format.html { redirect_to @meme, notice: 'Meme was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @meme }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @meme.errors, status: :unprocessable_entity }
  #     end
  # end

  # DELETE /memes/1
  # DELETE /memes/1.json
  def destroy
      @meme.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meme
      @meme = Meme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meme_params
      params.require(:meme).permit(:link, :user_id, :votes)
    end
end

meme_app/app/helpers/memes_helper.rb
module MemesHelper
end

meme_app/app/views/memes/_form.html.erb
<%= form_with(model: meme, local: true) do |form| %>
  <% if meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meme.errors.count, "error") %> prohibited this meme from being saved:</h2>

      <ul>
      <% meme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :votes %>
    <%= form.text_field :votes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

meme_app/app/views/memes/edit.html.erb
<h1>Editing Meme</h1>

<%= render 'form', meme: @meme %>

<%= link_to 'Show', @meme %> |
<%= link_to 'Back', memes_path %>

meme_app/app/views/memes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memes</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>User</th>
      <th>Votes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memes.each do |meme| %>
      <tr>
        <td><%= meme.link %></td>
        <td><%= meme.user_id %></td>
        <td><%= meme.votes %></td>
        <td><%= link_to 'Show', meme %></td>
        <td><%= link_to 'Edit', edit_meme_path(meme) %></td>
        <td><%= link_to 'Destroy', meme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meme', new_meme_path %>

meme_app/app/views/memes/new.html.erb
<h1>New Meme</h1>

<%= render 'form', meme: @meme %>

<%= link_to 'Back', memes_path %>

meme_app/app/views/memes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @meme.link %>
</p>

<p>
  <strong>User:</strong>
  <%= @meme.user_id %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @meme.votes %>
</p>

<%= link_to 'Edit', edit_meme_path(@meme) %> |
<%= link_to 'Back', memes_path %>